# Create an Event
POST  http://localhost:3000/api/events
Content-Type: application/json

{
  "name": "Cold play concert"
}

###
# Get an Event
GET  http://localhost:3000/api/events/56e435d3-b05d-4718-9671-d1f8726231a4
Content-Type: application/json

### 
# Create tickets and seat number
POST  http://localhost:3000/api/tickets
Content-Type: application/json

{
  "eventId": "56e435d3-b05d-4718-9671-d1f8726231a4",
  "seat": "3"
}

###
# Book that seat using the ticket number
PATCH  http://localhost:3000/api/tickets/f71eb879-5e05-4ada-b3ee-125642068d7d/book
Content-Type: application/json
